name: APK Security Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo with LFS (to pull APK)
    - name: Checkout repository (with LFS)
      uses: actions/checkout@v4
      with:
        lfs: true

    # 2. Setup Python for security tools
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3. Install dependencies & tools
    - name: Install tools
      run: |
        sudo apt update && sudo apt install -y unzip default-jdk android-tools-adb
        pip install mobsfscan gitleaks osv-scanner

    # Create reports folder
    - name: Create reports folder
      run: mkdir -p reports

    # 4. Static Analysis with MobSF
    - name: Run MobSFScan (SAST)
      run: |
        mobsfscan app.apk --json > reports/mobsfscan.json || true

    # 5. Secrets Scanning
    - name: Run Gitleaks
      run: |
        gitleaks detect --source . --report-path reports/gitleaks.json || true

    # 6. Dependency Vulnerability Scan
    - name: Run OSV Scanner (SCA)
      run: |
        osv-scanner --sbom=app.apk --format=json > reports/osv.json || true

    # 7. Dynamic Analysis – Launch Emulator
    - name: Launch Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: default
        arch: x86_64
        profile: Nexus 6
        script: ./scripts/dynamic_scan.sh

    # 8. Upload Reports
    - name: Upload security reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: reports/
