name: APK Security Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  apk-security:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo and pull APK from Git LFS
    - name: Checkout repository (with LFS)
      uses: actions/checkout@v4
      with:
        lfs: true

    # 2. Setup Python (required for MobSF, Gitleaks, OSV)
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3. Install system dependencies
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip default-jdk android-tools-adb openvpn wget curl

    # 4. Install Python security tools
    - name: Install security tools
      run: |
        # MobSFScan (Python)
        pip install mobsfscan
        # Gitleaks (binary)
        wget https://github.com/zricethezav/gitleaks/releases/download/v8.19.1/gitleaks_8.19.1_linux_x64.tar.gz -O gitleaks.tar.gz
        tar -xvzf gitleaks.tar.gz
        sudo mv gitleaks /usr/local/bin/
        gitleaks version
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Install OSV Scanner
      run: |
        # Fetch the latest release URL
        LATEST_RELEASE_URL=$(curl -s https://api.github.com/repos/google/osv-scanner/releases/latest | jq -r '.assets[] | select(.name == "osv-scanner-linux-amd64") | .browser_download_url')
         echo "Latest OSV Scanner URL: $LATEST_RELEASE_URL"
        # Check if the URL was found
        if [ "$LATEST_RELEASE_URL" != "null" ]; then
          # Download and install OSV Scanner
          wget "$LATEST_RELEASE_URL" -O osv-scanner
          chmod +x osv-scanner
          sudo mv osv-scanner /usr/local/bin/
          osv-scanner --version
        else
          echo "OSV Scanner binary for linux-amd64 not found in the latest release."
          exit 1
        fi


    # 5. Create reports folder
    - name: Create reports folder
      run: mkdir -p reports

    # 6. Connect to VPN
    - name: Connect to VPN
      env:
        VPN_EMAIL: ${{ secrets.VPN_EMAIL }}
        VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
      run: |
        sudo openvpn --config vpn/fastlink.ovpn --auth-user-pass <(echo -e "$VPN_EMAIL\n$VPN_PASSWORD") &
        sleep 15
        echo "[+] VPN connection attempted"
        curl -I https://internal-api.company.local || true

    # 7. Static Analysis (MobSF)
    - name: Run MobSFScan (Static Analysis)
      run: |
        mobsfscan apk/app.apk --json > reports/mobsfscan.json || true

    # 8. Secrets Scan (Gitleaks)
    - name: Run Gitleaks (Secrets Scan)
      run: |
        gitleaks detect --source . --report-path reports/gitleaks.json || true

    # 9. Dependency / SCA Scan (OSV Scanner)
    - name: Run OSV Scanner (Dependency Analysis)
      run: |
        osv-scanner --sbom=apk/app.apk --format=json > reports/osv.json || true

    # 10. Dynamic Analysis with Android Emulator
    - name: Launch Android Emulator & Run Dynamic Scan
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 35
        target: default
        arch: x86_64
        profile: Nexus 6
        script: ./scripts/dynamic_scan.sh

    # 11. Upload all reports as artifacts
    - name: Upload Security Reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: reports/**
